### ISSUE TITLE
Readme not working

### ISSUE THREAD

**Issue by gdupret** [BIRD-TAO/EDTPP#5]
Hi Haitao,

I don't understand your position here: If you follow the readme instructions the model doesn't train and it is not even parsing the command line. The changes I propose fix that. Clone the repo in a new directory and try for yourself.

Best,
Georges

**Comment by EDAPINENUT** [comment]
It is strange for I have tested the code. Maybe it is because the package Yaml and others have been updated. I will test the code soon.

**Comment by EDAPINENUT** [comment]
I find I have commented .train function.
I have fixed it. Thanks for your contribution.

**Comment by gdupret** [comment]
Hi!

Thank you!

Do you happen to have a description of the data format that I have to use
if I want to test your models on my data?

Best,
Georges

**Comment by EDAPINENUT** [comment]
Sorry， I just test these methods on the open dataset. You can run the data preprocessing codes and see what they should be like.
